### ISSUE TITLE
Example Query 7 is not working

### ISSUE THREAD

**Issue by gurnoor1990** [candYgene/pbg-ld#11]
Query 7 from the Examples

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>

SELECT
   str(?qtl_id) AS ?qtl_id
   str(?sgn_gene_id) AS ?sgn_gene_id
   str(?sgn_trans_id) AS ?sgn_trans_id
   str(?annot) AS ?annot
WHERE {
   GRAPH <http://europepmc.org/articles> {
      ?qtl a obo:SO_0000771 ;
         obo:RO_0003308 ?trait ;
         so:overlaps ?gene ;
         dcterms:identifier ?qtl_id .
      FILTER(?trait = obo:SP_0000366)
   }
   GRAPH <http://solgenomics.net/genome/Solanum_lycopersicum> {
      ?gene so:transcribed_to ?transcript ;
         dcterms:identifier ?sgn_gene_id .
      ?transcript rdfs:comment ?annot ;
         dcterms:identifier ?sgn_trans_id
   }
}
LIMIT 5
```

Returning zero entries.

**Comment by gurnoor1990** [comment]
I think problem in connecting to the GRAPH <http://solgenomics.net/genome/Solanum_lycopersicum>

**Comment by arnikz** [comment]
I suppose, you're referring to the dev branch. Indeed, there is no output because `so:overlaps` predicates are missing from the graph. I'll look into it.

**Comment by arnikz** [comment]
N.B.: Use another trait or omit the FILTER all together as the new QTL graph does not contain the ` obo:SP_0000366` trait.

**Comment by arnikz** [comment]
I can't reproduce the issue. The query above gives me:

qtl_id | sgn_gene_id | sgn_trans_id | annot
-- | -- | -- | --
PMC3464107_1_1 | Solyc05g053800.2 | Solyc05g053800.2.1 | Name: Solyc05g053800.2.1; Note: DNA repair protein Rad50 (AHRD V1 ***- A8IE27_TRITU); contains Interpro domain(s)  IPR004584  Recombination/repair protein Rad50 ; Ontology_term: GO:0030674; interpro2go_term: GO:0030870, GO:0005694, GO:0000166, GO:0006281; sifter_term: GO:0030674
PMC3464107_1_1 | Solyc05g053810.2 | Solyc05g053810.2.1 | Name: Solyc05g053810.2.1; Note: Serine hydroxymethyltransferase (AHRD V1 **** D2D306_GOSHI); contains Interpro domain(s)  IPR001085  Serine hydroxymethyltransferase ; Ontology_term: GO:0004372; interpro2go_term: GO:0006563, GO:0030170; sifter_term: GO:0004372
PMC3464107_1_1 | Solyc05g053820.2 | Solyc05g053820.2.1 | Name: Solyc05g053820.2.1; Note: UDP-glucosyltransferase family 1 protein (AHRD V1 **** C6KI44_CITSI); contains Interpro domain(s)  IPR002213  UDP-glucuronosyl/UDP-glucosyltransferase ; Ontology_term: GO:0010294; interpro2go_term: GO:0008152; sifter_term: GO:0010294
PMC3464107_1_1 | Solyc05g053830.2 | Solyc05g053830.2.1 | Name: Solyc05g053830.2.1; Note: Protein transport protein Sec23 (AHRD V1 ***- Q9LUG1_ARATH); contains Interpro domain(s)  IPR006896  Sec23/Sec24 trunk region ; Ontology_term: GO:0005515, GO:0005096; interpro2go_term: GO:0030127; sifter_term: GO:0005515, GO:0005096
PMC3464107_1_1 | Solyc05g053850.2 | Solyc05g053850.2.1 | Name: Solyc05g053850.2.1; Note: SELF PRUNING 5G; Ontology_term: GO:0008429; sifter_term: GO:0008429

Try the following (and pls attach the log):
```
docker system prune --all
cd pbg-ld
git pull
cd src
make clean
make
```

**Comment by gurnoor1990** [comment]
Working now. My file solanum_lycopersicum.ttl.gz was corrupt
