### ISSUE TITLE
Issue with Emsembl Plants release-33

### ISSUE THREAD

**Issue by c-martinez** [candYgene/pbg-ld#2]
While running `get_rdf.sh` I noticed that it failed to download some data files:

```
curl --stderr - -LO "ftp://ftp.ensemblgenomes.org/pub/plants/release-${ENSEMBLPLANTS_RELEASE}/rdf/solanum_lycopersicum/solanum_lycopersicum.ttl.gz" \
> && echo "http://plants.ensembl.org/Solanum_lycopersicum" > solanum_lycopersicum.ttl.graph
```

Resulted in:
```
curl: (9) Server denied you to change to the given directory
```

Browsing to `ftp://ftp.ensemblgenomes.org/pub/plants/`, it seems like release-36 does work. So perhaps just need to update the release number (but I don't know if that will break something else).

**Comment by arnikz** [comment]
@c-martinez Interesting, I've tried the same command and it works for me. It could be that the server was down for maintenance.

**Comment by c-martinez** [comment]
Really? Because even if I go to `ftp://ftp.ensemblgenomes.org/pub/plants/release-33/rdf/solanum_lycopersicum/solanum_lycopersicum.ttl.gz` from my browser, I get a `550 Failed to change directory.` error. Maybe I am not allowed to go there because of some firewall rule or something? Who knows... But if it works for you, then never mind.

**Comment by arnikz** [comment]
Ah, you're right. Indeed, it works with the (latest) release-36 but not with release-33. I can send an email to the Ensembl team. Thanks.

**Comment by arnikz** [comment]
The Ensembl team fixed this problem (due to a hardware failure on their backup system).
