### ISSUE TITLE
Upload new QTL graphs

### ISSUE THREAD

**Issue by gurnoor1990** [candYgene/pbg-ld#21]
- [x] tomato QTLs (n=167, [CSV](https://github.com/PBR/QTM/blob/dev/data/output/csv/tomato_qtl.csv))
- [x] potato QTLs (n=106, [CSV](https://github.com/PBR/QTM/blob/dev/data/output/csv/potato_qtl.csv))

**Comment by arnikz** [comment]
Please add a link to (commit hash of) the data.

**Comment by gurnoor1990** [comment]
Link to the new version of data

https://github.com/PBR/QTM/tree/data_potato/data/output/db

**Comment by arnikz** [comment]
Web API endpoint `/sumQTLs` returns:

```
"taxon_id","n_articles","n_qtls","n_qtls_with_loc"
"NCBITaxon:4113",8,108,64
"NCBITaxon:4081",13,216,170
```
