### ISSUE TITLE
Example Query 4 not working

### ISSUE THREAD

**Issue by gurnoor1990** [candYgene/pbg-ld#22]
This Query is not working, I think Uniprot data has been revised. No GO term associated to Ripening now

```PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX uniprot: <http://purl.uniprot.org/core/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>
PREFIX go: <http://www.geneontology.org/formats/oboInOwl#>

SELECT
   DISTINCT
   str(?gene_name) AS ?gene_name
   concat('[', ?sgn_gene_id, '](https://solgenomics.net/locus/Solyc00g005000.2/view)') AS ?sgn_gene_id
   concat('[', ?uniprot_acc, '](', ?prot, ')') AS ?uniprot_acc
   concat('[', ?uniprot_id, '](', ?prot, ')') AS ?uniprot_id
   str(?uniprot_des) AS ?uniprot_des
   str(?go_term) AS ?go_term
   concat('[', ?go_id, '](', ?go, ')') AS ?go_id
   str(?go_cat) AS ?go_cat
WHERE {
   GRAPH <http://www.uniprot.org/proteomes/Solanum_lycopersicum> {
      ?prot uniprot:classifiedWith ?go ;
          uniprot:encodedBy/skos:prefLabel ?gene_name
   }
   GRAPH <http://plants.ensembl.org/Solanum_lycopersicum> {
      ?prot dc:identifier ?uniprot_acc ;
          rdfs:label ?uniprot_id ;
          dc:description ?uniprot_des ;
          ^<http://rdf.ebi.ac.uk/terms/ensembl/CHECKSUM> ?ensembl_prot_id .
       ?ensembl_transcript_id so:translates_to ?ensembl_prot_id ;
          so:transcribed_from/dc:identifier ?sgn_gene_id .
   }
   GRAPH <http://purl.obolibrary.org/obo/go.owl> {
      ?go ?p ?o ;
         rdfs:label ?go_term ;
         go:id ?go_id ;
         go:hasOBONamespace ?go_cat .
      ?o bif:contains '( fruit AND ripening )' .
      FILTER regex(?go, obo:GO_)
   }
}
ORDER BY ?gene_name
```

**Comment by arnikz** [comment]
Hmm, I've got this error using the query:

```
Virtuoso 42000 Error The estimated execution time 323359 (sec) exceeds the limit of 400 (sec).
```

**Comment by gurnoor1990** [comment]
Runs  after 
make restart-srv 

Similar to Issue #31

**Comment by matthijsbrouwer** [comment]
It does seem to work (at least circumventing the timeout warning) with
``` sparql
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX uniprot: <http://purl.uniprot.org/core/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>
PREFIX go: <http://www.geneontology.org/formats/oboInOwl#>

SELECT
   DISTINCT
   str(?gene_name) AS ?gene_name
   concat('[', ?sgn_gene_id, '](https://solgenomics.net/locus/Solyc00g005000.2/view)') AS ?sgn_gene_id
   concat('[', ?uniprot_acc, '](', ?prot, ')') AS ?uniprot_acc
   concat('[', ?uniprot_id, '](', ?prot, ')') AS ?uniprot_id
   str(?uniprot_des) AS ?uniprot_des
   str(?go_term) AS ?go_term
   concat('[', ?go_id, '](', ?go, ')') AS ?go_id
   str(?go_cat) AS ?go_cat
FROM NAMED <http://www.uniprot.org/proteomes/Solanum_lycopersicum>
FROM NAMED <http://plants.ensembl.org/Solanum_lycopersicum>
FROM NAMED <http://purl.obolibrary.org/obo/go.owl>
WHERE {
   GRAPH ?g1 {
      ?prot uniprot:classifiedWith ?go ;
          uniprot:encodedBy/skos:prefLabel ?gene_name
   }
   GRAPH ?g2 {
      ?prot dc:identifier ?uniprot_acc ;
          rdfs:label ?uniprot_id ;
          dc:description ?uniprot_des ;
          ^<http://rdf.ebi.ac.uk/terms/ensembl/CHECKSUM> ?ensembl_prot_id .
       ?ensembl_transcript_id so:translates_to ?ensembl_prot_id ;
          so:transcribed_from/dc:identifier ?sgn_gene_id .
   }
   GRAPH ?g3 {
      ?go ?p ?o ;
         rdfs:label ?go_term ;
         go:id ?go_id ;
         go:hasOBONamespace ?go_cat .
      ?o bif:contains '( fruit AND ripening )' .
      FILTER regex(?go, obo:GO_)
   }
}
ORDER BY ?gene_name
```
resulting in


gene_name | sgn_gene_id | uniprot_acc | uniprot_id | uniprot_des | go_term | go_id | go_cat
-- | -- | -- | -- | -- | -- | -- | --
ACO1 | [Solyc07g049530.2](https://solgenomics.net/locus/Solyc00g005000.2/view) | [P05116](http://purl.uniprot.org/uniprot/P05116) | [ACCO1_SOLLC](http://purl.uniprot.org/uniprot/P05116) | 1-aminocyclopropane-1-carboxylate oxidase 1 | fruit ripening | [GO:0009835](http://purl.obolibrary.org/obo/GO_0009835) | biological_process
ACO3 | [Solyc09g089580.2](https://solgenomics.net/locus/Solyc00g005000.2/view) | [P10967](http://purl.uniprot.org/uniprot/P10967) | [ACCH3_SOLLC](http://purl.uniprot.org/uniprot/P10967) | 1-aminocyclopropane-1-carboxylate oxidase homolog | fruit ripening | [GO:0009835](http://purl.obolibrary.org/obo/GO_0009835) | biological_process
ACO4 | [Solyc07g049550.2](https://solgenomics.net/locus/Solyc00g005000.2/view) | [P24157](http://purl.uniprot.org/uniprot/P24157) | [ACCO4_SOLLC](http://purl.uniprot.org/uniprot/P24157) | 1-aminocyclopropane-1-carboxylate oxidase 4 | fruit ripening | [GO:0009835](http://purl.obolibrary.org/obo/GO_0009835) | biological_process
ACS2 | [Solyc01g095080.2](https://solgenomics.net/locus/Solyc00g005000.2/view) | [P18485](http://purl.uniprot.org/uniprot/P18485) | [1A12_SOLLC](http://purl.uniprot.org/uniprot/P18485) | 1-aminocyclopropane-1-carboxylate synthase 2 | fruit ripening | [GO:0009835](http://purl.obolibrary.org/obo/GO_0009835) | biological_process
ACS3 | [Solyc02g091990.2](https://solgenomics.net/locus/Solyc00g005000.2/view) | [Q42881](http://purl.uniprot.org/uniprot/Q42881) | [1A13_SOLLC](http://purl.uniprot.org/uniprot/Q42881) | 1-aminocyclopropane-1-carboxylate synthase 3 | fruit ripening | [GO:0009835](http://purl.obolibrary.org/obo/GO_0009835) | biological_process
ARF2A | [Solyc03g118290.2](https://solgenomics.net/locus/Solyc00g005000.2/view) | [Q2LAJ3](http://purl.uniprot.org/uniprot/Q2LAJ3) | [Q2LAJ3_SOLLC](http://purl.uniprot.org/uniprot/Q2LAJ3) | Auxin response factor | fruit ripening, climacteric | [GO:0009836](http://purl.obolibrary.org/obo/GO_0009836) | biological_process
ARF2A | [Solyc03g118290.2](https://solgenomics.net/locus/Solyc00g005000.2/view) | [Q2LAJ3](http://purl.uniprot.org/uniprot/Q2LAJ3) | [Q2LAJ3_SOLLC](http://purl.uniprot.org/uniprot/Q2LAJ3) | Auxin response factor | fruit ripening | [GO:0009835](http://purl.obolibrary.org/obo/GO_0009835) | biological_process
ARF2B | [Solyc12g042070.1](https://solgenomics.net/locus/Solyc00g005000.2/view) | [K4DF01](http://purl.uniprot.org/uniprot/K4DF01) | [K4DF01_SOLLC](http://purl.uniprot.org/uniprot/K4DF01) | Auxin response factor | fruit ripening | [GO:0009835](http://purl.obolibrary.org/obo/GO_0009835) | biological_process
GP1 | [Solyc05g005560.2](https://solgenomics.net/locus/Solyc00g005000.2/view) | [Q40161](http://purl.uniprot.org/uniprot/Q40161) | [GP1_SOLLC](http://purl.uniprot.org/uniprot/Q40161) | Polygalacturonase-1 non-catalytic subunit beta | fruit ripening | [GO:0009835](http://purl.obolibrary.org/obo/GO_0009835) | biological_process
PG2 | [Solyc10g080210.1](https://solgenomics.net/locus/Solyc00g005000.2/view) | [P05117](http://purl.uniprot.org/uniprot/P05117) | [PGLR_SOLLC](http://purl.uniprot.org/uniprot/P05117) | Polygalacturonase-2 | fruit ripening | [GO:0009835](http://purl.obolibrary.org/obo/GO_0009835) | biological_process
PME1.9 | [Solyc07g064170.2](https://solgenomics.net/locus/Solyc00g005000.2/view) | [P14280](http://purl.uniprot.org/uniprot/P14280) | [PME1_SOLLC](http://purl.uniprot.org/uniprot/P14280) | Pectinesterase 1 | fruit ripening | [GO:0009835](http://purl.obolibrary.org/obo/GO_0009835) | biological_process
PME2.1 | [Solyc07g064180.2](https://solgenomics.net/locus/Solyc00g005000.2/view) | [P09607](http://purl.uniprot.org/uniprot/P09607) | [PME21_SOLLC](http://purl.uniprot.org/uniprot/P09607) | Pectinesterase 2.1 | fruit ripening | [GO:0009835](http://purl.obolibrary.org/obo/GO_0009835) | biological_process
