### ISSUE TITLE
All example queries with the following graphs are not running 

### ISSUE THREAD

**Issue by gurnoor1990** [candYgene/pbg-ld#31]
- http://solgenomics.net/genome/Solanum_lycopersicum
-  http://solgenomics.net/genome/Solanum_pennellii
- http://solgenomics.net/genome/Solanum_tuberosum
- http://plants.ensembl.org/Solanum_lycopersicum
 - http://plants.ensembl.org/Solanum_tuberosum  

Error Message is 
```
Virtuoso 42000 Error The estimated execution time 426 (sec) exceeds the limit of 400 (sec).

```

For Example Query 1

```
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT
   str(?feature_name) AS ?feature_name
   ?feature_id
   COUNT(*) AS ?n
WHERE {
   GRAPH <http://solgenomics.net/genome/Solanum_lycopersicum> {
   # http://solgenomics.net/genome/Solanum_pennellii
   # http://solgenomics.net/genome/Solanum_tuberosum
   # http://plants.ensembl.org/Solanum_lycopersicum
   # http://plants.ensembl.org/Solanum_tuberosum                             
      ?ft a ?feature_type .
      FILTER regex(?feature_type, obo:SO_) .
      BIND(concat('[', replace(replace(str(?feature_type), '.+\\/', ''), '_', ':'), '](', ?feature_type, ')') AS ?feature_id)
   }
   GRAPH <http://purl.obolibrary.org/obo/so.owl> {
      ?feature_type rdfs:label ?feature_name
   }
}
GROUP BY ?feature_name ?feature_id
ORDER BY DESC(?n)
```

**Comment by gurnoor1990** [comment]
Error vanishes after 
make restart-srv

**Comment by matthijsbrouwer** [comment]
They do seem to run (even all together in one query) with
``` sparql
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT
   str(?g1) AS ?g1
   str(?feature_name) AS ?feature_name
   ?feature_id
   COUNT(*) AS ?n
FROM NAMED <http://solgenomics.net/genome/Solanum_lycopersicum>
FROM NAMED <http://solgenomics.net/genome/Solanum_pennellii>
FROM NAMED <http://solgenomics.net/genome/Solanum_tuberosum>
FROM NAMED <http://plants.ensembl.org/Solanum_lycopersicum>
FROM NAMED <http://plants.ensembl.org/Solanum_tuberosum>
FROM NAMED <http://purl.obolibrary.org/obo/so.owl>
WHERE {
   GRAPH ?g1 {                             
      ?ft a ?feature_type .
      FILTER regex(?feature_type, obo:SO_) .
      BIND(concat('[', replace(replace(str(?feature_type), '.+\\/', ''), '_', ':'), '](', ?feature_type, ')') AS ?feature_id)
   }
   GRAPH ?g2 {
      ?feature_type rdfs:label ?feature_name
   }
}
GROUP BY ?g1 ?g2 ?feature_name ?feature_id
ORDER BY ASC(?g1) DESC(?n)
```
resulting in


g1 | feature_name | feature_id | n
-- | -- | -- | --
http://plants.ensembl.org/Solanum_lycopersicum | exon | [SO:0000147](http://purl.obolibrary.org/obo/SO_0000147) | 162535
http://plants.ensembl.org/Solanum_lycopersicum | protein_coding_primary_transcript | [SO:0000120](http://purl.obolibrary.org/obo/SO_0000120) | 34725
http://plants.ensembl.org/Solanum_lycopersicum | protein_coding_gene | [SO:0001217](http://purl.obolibrary.org/obo/SO_0001217) | 33785
http://plants.ensembl.org/Solanum_lycopersicum | miRNA_gene | [SO:0001265](http://purl.obolibrary.org/obo/SO_0001265) | 3153
http://plants.ensembl.org/Solanum_lycopersicum | miRNA | [SO:0000276](http://purl.obolibrary.org/obo/SO_0000276) | 3153
http://plants.ensembl.org/Solanum_lycopersicum | tRNA_gene | [SO:0001272](http://purl.obolibrary.org/obo/SO_0001272) | 908
http://plants.ensembl.org/Solanum_lycopersicum | snoRNA | [SO:0000275](http://purl.obolibrary.org/obo/SO_0000275) | 390
http://plants.ensembl.org/Solanum_lycopersicum | snoRNA_gene | [SO:0001267](http://purl.obolibrary.org/obo/SO_0001267) | 390
http://plants.ensembl.org/Solanum_lycopersicum | snRNA_gene | [SO:0001268](http://purl.obolibrary.org/obo/SO_0001268) | 255
http://plants.ensembl.org/Solanum_lycopersicum | snRNA | [SO:0000274](http://purl.obolibrary.org/obo/SO_0000274) | 255
http://plants.ensembl.org/Solanum_lycopersicum | rRNA | [SO:0000252](http://purl.obolibrary.org/obo/SO_0000252) | 94
http://plants.ensembl.org/Solanum_lycopersicum | rRNA_gene | [SO:0001637](http://purl.obolibrary.org/obo/SO_0001637) | 94
http://plants.ensembl.org/Solanum_lycopersicum | pseudogenic_tRNA | [SO:0000778](http://purl.obolibrary.org/obo/SO_0000778) | 76
http://plants.ensembl.org/Solanum_lycopersicum | RNA | [SO:0000356](http://purl.obolibrary.org/obo/SO_0000356) | 2
http://plants.ensembl.org/Solanum_tuberosum | exon | [SO:0000147](http://purl.obolibrary.org/obo/SO_0000147) | 177518
http://plants.ensembl.org/Solanum_tuberosum | protein_coding_primary_transcript | [SO:0000120](http://purl.obolibrary.org/obo/SO_0000120) | 56215
http://plants.ensembl.org/Solanum_tuberosum | protein_coding_gene | [SO:0001217](http://purl.obolibrary.org/obo/SO_0001217) | 39021
http://plants.ensembl.org/Solanum_tuberosum | miRNA | [SO:0000276](http://purl.obolibrary.org/obo/SO_0000276) | 1203
http://plants.ensembl.org/Solanum_tuberosum | miRNA_gene | [SO:0001265](http://purl.obolibrary.org/obo/SO_0001265) | 1203
http://plants.ensembl.org/Solanum_tuberosum | snoRNA | [SO:0000275](http://purl.obolibrary.org/obo/SO_0000275) | 938
http://plants.ensembl.org/Solanum_tuberosum | tRNA_gene | [SO:0001272](http://purl.obolibrary.org/obo/SO_0001272) | 938
http://plants.ensembl.org/Solanum_tuberosum | snoRNA_gene | [SO:0001267](http://purl.obolibrary.org/obo/SO_0001267) | 938
http://plants.ensembl.org/Solanum_tuberosum | snRNA | [SO:0000274](http://purl.obolibrary.org/obo/SO_0000274) | 392
http://plants.ensembl.org/Solanum_tuberosum | snRNA_gene | [SO:0001268](http://purl.obolibrary.org/obo/SO_0001268) | 392
http://plants.ensembl.org/Solanum_tuberosum | pseudogenic_tRNA | [SO:0000778](http://purl.obolibrary.org/obo/SO_0000778) | 332
http://plants.ensembl.org/Solanum_tuberosum | rRNA | [SO:0000252](http://purl.obolibrary.org/obo/SO_0000252) | 107
http://plants.ensembl.org/Solanum_tuberosum | rRNA_gene | [SO:0001637](http://purl.obolibrary.org/obo/SO_0001637) | 107
http://plants.ensembl.org/Solanum_tuberosum | RNA | [SO:0000356](http://purl.obolibrary.org/obo/SO_0000356) | 1
http://solgenomics.net/genome/Solanum_lycopersicum | exon | [SO:0000147](http://purl.obolibrary.org/obo/SO_0000147) | 160001
http://solgenomics.net/genome/Solanum_lycopersicum | CDS | [SO:0000316](http://purl.obolibrary.org/obo/SO_0000316) | 157233
http://solgenomics.net/genome/Solanum_lycopersicum | intron | [SO:0000188](http://purl.obolibrary.org/obo/SO_0000188) | 125276
http://solgenomics.net/genome/Solanum_lycopersicum | protein_coding_gene | [SO:0001217](http://purl.obolibrary.org/obo/SO_0001217) | 34725
http://solgenomics.net/genome/Solanum_lycopersicum | protein_coding_primary_transcript | [SO:0000120](http://purl.obolibrary.org/obo/SO_0000120) | 34725
http://solgenomics.net/genome/Solanum_lycopersicum | genetic_marker | [SO:0001645](http://purl.obolibrary.org/obo/SO_0001645) | 30718
http://solgenomics.net/genome/Solanum_lycopersicum | three_prime_UTR | [SO:0000205](http://purl.obolibrary.org/obo/SO_0000205) | 15343
http://solgenomics.net/genome/Solanum_lycopersicum | five_prime_UTR | [SO:0000204](http://purl.obolibrary.org/obo/SO_0000204) | 13548
http://solgenomics.net/genome/Solanum_lycopersicum | chromosome | [SO:0000340](http://purl.obolibrary.org/obo/SO_0000340) | 13
http://solgenomics.net/genome/Solanum_lycopersicum | genome | [SO:0001026](http://purl.obolibrary.org/obo/SO_0001026) | 1
http://solgenomics.net/genome/Solanum_pennellii | exon | [SO:0000147](http://purl.obolibrary.org/obo/SO_0000147) | 278874
http://solgenomics.net/genome/Solanum_pennellii | CDS | [SO:0000316](http://purl.obolibrary.org/obo/SO_0000316) | 252950
http://solgenomics.net/genome/Solanum_pennellii | intron | [SO:0000188](http://purl.obolibrary.org/obo/SO_0000188) | 204027
http://solgenomics.net/genome/Solanum_pennellii | protein_coding_primary_transcript | [SO:0000120](http://purl.obolibrary.org/obo/SO_0000120) | 48923
http://solgenomics.net/genome/Solanum_pennellii | protein_coding_gene | [SO:0001217](http://purl.obolibrary.org/obo/SO_0001217) | 44965
http://solgenomics.net/genome/Solanum_pennellii | genetic_marker | [SO:0001645](http://purl.obolibrary.org/obo/SO_0001645) | 2225
http://solgenomics.net/genome/Solanum_pennellii | chromosome | [SO:0000340](http://purl.obolibrary.org/obo/SO_0000340) | 13
http://solgenomics.net/genome/Solanum_pennellii | genome | [SO:0001026](http://purl.obolibrary.org/obo/SO_0001026) | 1
http://solgenomics.net/genome/Solanum_tuberosum | CDS | [SO:0000316](http://purl.obolibrary.org/obo/SO_0000316) | 202449
http://solgenomics.net/genome/Solanum_tuberosum | exon | [SO:0000147](http://purl.obolibrary.org/obo/SO_0000147) | 165573
http://solgenomics.net/genome/Solanum_tuberosum | intron | [SO:0000188](http://purl.obolibrary.org/obo/SO_0000188) | 109913
http://solgenomics.net/genome/Solanum_tuberosum | reagent | [SO:0000695](http://purl.obolibrary.org/obo/SO_0000695) | 70326
http://solgenomics.net/genome/Solanum_tuberosum | protein_coding_primary_transcript | [SO:0000120](http://purl.obolibrary.org/obo/SO_0000120) | 56215
http://solgenomics.net/genome/Solanum_tuberosum | protein_coding_gene | [SO:0001217](http://purl.obolibrary.org/obo/SO_0001217) | 39028
http://solgenomics.net/genome/Solanum_tuberosum | genetic_marker | [SO:0001645](http://purl.obolibrary.org/obo/SO_0001645) | 5692
http://solgenomics.net/genome/Solanum_tuberosum | chromosome | [SO:0000340](http://purl.obolibrary.org/obo/SO_0000340) | 13
http://solgenomics.net/genome/Solanum_tuberosum | genome | [SO:0001026](http://purl.obolibrary.org/obo/SO_0001026) | 1

**Comment by matthijsbrouwer** [comment]
And to improve performance, it can be simplified to
``` sparql
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT
   STR(?g1) AS ?g1
   STR(?feature_name) AS ?feature_name
   CONCAT('[', replace(replace(str(?feature_type), '.+\\/', ''), '_', ':'), '](', ?feature_type, ')') AS ?feature_id
   COUNT(*) AS ?n
FROM NAMED <http://solgenomics.net/genome/Solanum_lycopersicum>
FROM NAMED <http://solgenomics.net/genome/Solanum_pennellii>
FROM NAMED <http://solgenomics.net/genome/Solanum_tuberosum>
FROM NAMED <http://plants.ensembl.org/Solanum_lycopersicum>
FROM NAMED <http://plants.ensembl.org/Solanum_tuberosum>
FROM NAMED <http://purl.obolibrary.org/obo/so.owl>
WHERE {
   GRAPH ?g1 {                             
      ?ft a ?feature_type .
   }
   GRAPH ?g2 {
      ?feature_type rdfs:label ?feature_name
   }
}
GROUP BY ?g1 ?g2 ?feature_name ?feature_type
ORDER BY ASC(?g1) DESC(?n)
```
