### ISSUE TITLE
Some flanking markers require additional validation & post-processing

### ISSUE THREAD

**Issue by arnikz** [candYgene/pbg-ld#34]
For example, `QTL:3464107_4_15` is associated with two (flanking) markers:

- `TG194-J1` tagged as
   - `TG194`
      - `http://localhost:8890/genome/Solanum_lycopersicum/variation/gene72_0-i22`; chromosome 11:2947789-2948311
      - `http://localhost:8890/genome/Solanum_lycopersicum/variation/gene73_0-i22`; chromosome 11:2947789-2948309
  - `J1`
     - `http://localhost:8890/genome/Solanum_pennellii/variation/cLES-5-J1`; chromosome 1:95577802-95577596 (which [is orthologous to](http://semanticscience.org/resource/SIO_000558) `http://localhost:8890/genome/Solanum_lycopersicum/variation/gene358_0-i2`; chromosome 1:85319942-85322549)

**Comment by gurnoor1990** [comment]
Solved in the new data! which will be updated while solving issue #21  

3464107	4	15	TG194-J1
http://solgenomics.net/genome/Solanum_lycopersicum/variation/gene358_0-i2;
http://solgenomics.net/genome/Solanum_lycopersicum/variation/gene72_0-i22;
http://solgenomics.net/genome/Solanum_lycopersicum/variation/gene73_0-i22;
http://solgenomics.net/genome/Solanum_pennellii/variation/cLES-5-J1

**Comment by arnikz** [comment]
Not really as it requires revision of this code:

https://github.com/candYgene/pbg-ld/blob/55ac92e315566b124a07e141726d3b126edda726/src/update_rdf.sql#L372-L411

**Comment by arnikz** [comment]
In fact, the code is correct and can't be "smarter". After all, it's upon the curator to decide if `J1` is (not) the same marker as `cLES-5-J1`.
