### ISSUE TITLE
Failed to connect to host

### ISSUE THREAD

**Issue by mbeavitt** [candYgene/pbg-ld#51]
Hello!

I was trying to access this tool and was wondering if someone could help me troubleshoot an issue.

When running the command:

`ansible-playbook -i inventory playbook.yml`

I encounter the error:

```
PLAY [all] ***********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************
fatal: [pbg-ld.candygene-nlesc.surf-hosted.nl]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname pbg-ld.candygene-nlesc.surf-hosted.nl: Name or service not known", "unreachable": true}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************
pbg-ld.candygene-nlesc.surf-hosted.nl : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
```

Is this because the host is temporarily down, or is the host no longer supported?
Alternatively, is the user meant to setup a database host? 

Look forward to hearing from you!

Michael

**Comment by arnikz** [comment]
Hi,

> When running the command:
> 
> `ansible-playbook -i inventory playbook.yml`
> 
> I encounter the error:

Indeed, this host was only accessible to the team members. So, you should change it to something else.

> Ah, also, I previously tried using docker-compose after logging into github from the terminal, and was denied access to the images:
> 

Similarly, the packages (e.g., docker images) are only accessible to the team members but you could try to build those images yourself. Sorry, I can't help you further as I moved on.

**Comment by mbeavitt** [comment]
Thanks for the reply! I'll see what I can do.

Michael
